### ISSUE TITLE
serviceMonitor additionalLabels

### ISSUE THREAD

**Issue by ebCrypto** [bjw-s/helm-charts#110]
# Details

**Describe the solution you'd like:**

I was wondering if it would make sense to support additionalLabels similarly to see this: https://github.com/stefanprodan/podinfo/blob/fdd0a0b7dad56fbc6bb71e7e8badee5a3a3c663f/charts/podinfo/templates/servicemonitor.yaml#L8

**Comment by bjw-s** [comment]
Thanks for reporting! I'll be sure to take a look. I'm sure I can get something workable going

**Comment by bjw-s** [comment]
Well, there's bad news and good news... Starting with the bad: I will not be implementing this after all.
Because of the good news: it's already implemented 😆 

You can use `serviceMonitor._name_.labels` to set any serviceMonitor-specific labels. (I've added a unit test to the latest development branch to verify.)

If you have any other questions regarding this feel free to reach out.
