### ISSUE TITLE
Clarify this repo's purpose?

### ISSUE THREAD

**Issue by johanneskastl** [bjw-s/helm-charts#121]
https://github.com/bjw-s/helm-charts/blob/bfc48a7eeee20489815a2208c421250008372971/README.md?plain=1#L17

> This repo contains Helm charts that I have developed to run applications in my [home Kubernetes cluster](https://github.com/bjw-s/home-ops/).

Isn't this only containing the library chart? Or are there other charts that I just failed to find? :-)

**Comment by dberardo-com** [comment]
more specifically, i have a question on the pod-gateway chart. where should i post it ? here or on discord ?

**Comment by bjw-s** [comment]
> exacgtly, i was reading the deprecation notes from: [k8s-at-home/charts#1761](https://github.com/k8s-at-home/charts/issues/1761) and expected to find all the older hlem charts in this repo, however a helm search leads to:

Your expectation would be inccorect :) We have kept all the old helm charts over at the KaH org, but I will definitely not be maintaining / hosting any of those charts here unless I have a need for a custom chart that I can't cover with the app-template.

This is also the answer to @johanneskastl for why there aren't any other charts in this repo (yet): I haven't had a need that I couldn't cover with my app-template chart.

> more specifically, i have a question on the pod-gateway chart. where should i post it ? here or on discord ?

Since I don't build/host/maintain the pod-gateway chart my repo would definitely not be the place. You are however welcome to join the KaH Discord and see if you can find an answer to your question there. Also, the new (and original) chart maintainer for pod-gateway hosts it over here: https://github.com/angelnu/pod-gateway

**Comment by johanneskastl** [comment]
Thanks for the reply, Bernd.

When you say you could use the app-template to cover your needs, did you create a helm chart on the fly / locally from the app template? I understood it to be a template that one can take and create a helm chart out of.

**Comment by bjw-s** [comment]
Not entirely, the app-template is pretty much a very simple implementation of a chart that uses the common library (as were almost all the charts that we were maintaining over at KaH which is one of the main reasons we deprecated them). 

An example of how I use it in my k8s cluster can be found here: https://github.com/bjw-s/home-ops/blob/main/kubernetes/cluster-0/apps/home-automation/frigate/app/helmrelease.yaml
