### ISSUE TITLE
Release notes for 2.0?

### ISSUE THREAD

**Issue by evanrich** [bjw-s/helm-charts#194]
I've looked all over but can't find a release notes file for the 2.0 release, is it somewhere I'm missing?

**Comment by bjw-s** [comment]
Release notes are normally kept in the following locations:
- Chart.yaml annotations:
	- https://github.com/bjw-s/helm-charts/blob/main/charts/other/app-template/Chart.yaml#L15
	- https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml#L16
- PR description: https://github.com/bjw-s/helm-charts/pull/189

But since this 2.0 upgrade has touched so many areas it's almost impossible to keep a full changelog. Therefore some additional upgrade instructions have been written: https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template#upgrade-instructions

**Comment by evanrich** [comment]
thanks! I also just found the link to the 1.x vs 2.x format here: https://bjw-s.github.io/helm-charts/docs/app-template/#from-1xx-to-20x
