### ISSUE TITLE
VPN addon for v2

### ISSUE THREAD

**Issue by rishikanthc** [bjw-s/helm-charts#201]
# Details

Request that the VPN addon (That was there in v1.5.5) be added in v2 as well

**Anything else you would like to add:**
The add-ons were a great functionality that was included in v1.5.1
Would really appreciate it if it could be made available in the latest version as well.

**Comment by bjw-s** [comment]
Taking the add-ons out was a very intentional decision and I currently have no plans to reinstate them. For example, to return the VPN add-on functionality it is just a matter of adding a 'gluetun` container to the pod: https://github.com/bjw-s/home-ops/blob/45316aa03a93ac4e85c8155d36b9c143ad1e1465/kubernetes/cluster-0/apps/downloads/qbittorrent/app/helmrelease.yaml#L57
