### ISSUE TITLE
Persistence items are disabled by default but the docs say the opposite (app-template)

### ISSUE THREAD

**Issue by phybros** [bjw-s/helm-charts#251]
The docs for app-template say that we can leave `enabled: true` out of our persistence items but in fact they appear to be disabled by default according to https://github.com/bjw-s/helm-charts/blob/bd032c5ab33edad52f7a218a42ff2d51f4a58c3a/charts/library/common/values.yaml#L614C8-L614C8

This bit me just now, I left `enabled` off the yaml and sure enough the items were disabled. Seems like maybe just a docs update is required?

**Comment by haraldkoch** [comment]
I think that this is only true for the `config` item, and only because it's in the `values.yaml` file as a (disabled) example.

**Comment by phybros** [comment]
Makes sense. Sounds like a pretty straightforward docs update. I can submit
a PR

**Comment by qlonik** [comment]
Hey, I encountered this too, when creating a `type: persistentVolumeClaim` entry. It seems that because of the strict check for `$pvc.enabled` [here](https://github.com/bjw-s/helm-charts/blob/bd032c5ab33edad52f7a218a42ff2d51f4a58c3a/charts/library/common/templates/render/_pvcs.tpl#L7C12-L7C28), it behaves like this. Should this branch instead check if the key is either not present or present and set to true? Then it should get back to the defaulting to true scenario as docs say.

**Comment by bjw-s** [comment]
> Hey, I encountered this too, when creating a `type: persistentVolumeClaim` entry. It seems that because of the strict check for `$pvc.enabled` [here](https://github.com/bjw-s/helm-charts/blob/bd032c5ab33edad52f7a218a42ff2d51f4a58c3a/charts/library/common/templates/render/_pvcs.tpl#L7C12-L7C28), it behaves like this. Should this branch instead check if the key is either not present or present and set to true? Then it should get back to the defaulting to true scenario as docs say.

Good find! This is definitely an issue, as it will prevent PVC's from being created when the `enabled` flag isn't set. I will fix that in an upcoming version.

As for the `config` persistence item, @haraldkoch is correct that this should be the only "exception" since it is already present but disabled in the default values for legacy purposes. V3 will drop these default values, making it so that all persistence items adhere to the "enabled by default" behavior.
